### ISSUE TITLE
Feature #5 Search Entries

### ISSUE THREAD

**Issue by paulpark330** [paulpark330/code-journal#10]
## 💰 Motivation

If a user wants to search for an entry, they should be able to find the entry.

## 📐 Plan

Allow users to search an entry from the entries view.

## ✅ Task List

- [x] Search text input only visible in entries view
- [x] When a user searches for the title of the entry,
- [x] They should be able to see the searched entry and everything hidden
- [x] Remove all CSS styling that had no affect or was otherwise unnecessary.
- [x] Test all functionality again in a private browsing session.
- [x] Fix all errors.
